config/routes.rb
Br2::Application.routes.draw do
  get 'online_books' => 'online_books#index'
  get 'online_books/:designation' => 'online_books#show', constraints: { designation: /[-A-Za-z0-9.]+/ }

  get 'online_books/show_thumbnails/:designation/:page_designation' => 'online_books#show_thumbnails', constraints: { designation: /[-A-Za-z0-9.]+/ }
  get 'online_books/show_page/:designation/:page_designation' => 'online_books#show_page', constraints: { designation: /[-A-Za-z0-9.]+/ }
  get 'online_books/zoom_page/:designation/:page_designation' => 'online_books#zoom_page', constraints: { designation: /[-A-Za-z0-9.]+/ }

  get 'online_pages/show_page/:book_designation/:page_designation' => 'online_pages#show', constraints: { book_designation: /[-A-Za-z0-9.]+/ }

  resources :online_pages

  resources :file_patterns

  resources :digital_assets

  resources :digital_collections

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :collection_components
  resources :component_levels

  

end

app/models/online_page.rb
class OnlinePage < ActiveRecord::Base
	belongs_to :online_book
	belongs_to :digital_asset
end

app/controllers/online_pages_controller.rb
class OnlinePagesController < ApplicationController
	def permitted_params
		# params.require(:digital_asset).permit al_asset: [ { :page_number, :page_transcript } ]
		params.permit(:id, :submit, :authenticity_token, :_method, :commit, :action, :controller, :utf8, digital_asset: [ :id, :page_number, :page_transcript ])
	end

	def index
		@online_pages = OnlinePage.all
	end

	def old_show
		# @online_page = OnlinePage.find_by_designation(params[:designation])
		@online_page = OnlinePage.find(params[:id])
	end

	def edit
		@online_page = OnlinePage.find(params[:id])
	end

	def update
		@online_page = OnlinePage.find(permitted_params[:id])
		if @online_page.digital_asset.update_attributes(permitted_params[:digital_asset])
			# redirect_to :action => 'show', :id => @online_page
			redirect_to :action => 'index'
		else
			render :action => 'edit'
		end
	end

	def lookup_page book_designation, page_designation
		## A helper method.
		@online_book = OnlineBook.find_by_designation(book_designation)
		matching_pages = @online_book.pages.select { |x| x.designation == page_designation }
		page = matching_pages[0]
		@online_page =
			{
				# id: page.id,
				id: page.designation.to_i,
				height: page.image_height,
				width: page.image_width,
				derivative_height: (100).to_s,
				derivative_width: (100 * (page.image_width.to_f / page.image_height.to_f)).to_i.to_s,
				page_side: 'L',
				url: page.url,
				derivative_url: page.derivative_url,
				transcript: page.page_transcript,
				# designation: page.collection_component.designation
				designation: page.designation
			}

		@next_page = @online_page
		@prev_page = @online_page

	## Get all pages for thumbnails:
	unsorted_pages_array = @online_book.pages.map do |page|
			{
				# id: page.id,
				id: page.designation.to_i,
				height: page.image_height,
				width: page.image_width,
				derivative_height: (100).to_s,
				derivative_width: (100 * (page.image_width.to_f / page.image_height.to_f)).to_i.to_s,
				page_side: 'L',
				url: page.url,
				derivative_url: page.derivative_url,
				transcript: page.page_transcript,
				# designation: page.collection_component.designation
				designation: page.designation
			}
		end
		@pages_hash = {};
		unsorted_pages_array.each { |i|
			@pages_hash[i[:id]] = i
		}

		# Sort the array (which is keyed by id) according to page designation:
		@page_num_array = unsorted_pages_array.map { |a| a[:id] }.sort { |b,c| @pages_hash[b][:designation].to_i <=> @pages_hash[c][:designation].to_i }

		@user_ip = request.remote_ip


	end

	def show
		lookup_page params[:book_designation], params[:page_designation]

		respond_to do |responder|
			responder.html { render 'show.html', layout: 'new' }
			# responder.json { render json: @online_book_json_data  }
		end
	end

	def show_transcript
		lookup_page params[:book_designation], params[:page_designation]

		respond_to do |responder|
			responder.html { render 'transcript.html', layout: 'new' }
			# responder.json { render json: @online_book_json_data  }
		end
	end

end

app/views/online_pages/_scripts_partial.html.haml
%script
	!= "book_data = #{@online_book.to_json};"
	!= "page_num_array = #{@page_num_array};"
	!= "user_ip = '#{@user_ip}';"


:javascript


	// Google Analytics
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-34936065-1']);
	_gaq.push(['_trackPageview']);

	(function() {
	  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();
	// GA Event:
	_gaq.push(['_trackEvent',
		'Page Viewed by Type',
		'Alfred Rosenberg diary',
	]);


	$(function() {

		oara_build_feedback_url = function() {
		    // return a link to the Google feedback form
		    google_form_key = 'dFMzQ0RLU19nNXFRTkg1dFFJNXhfSmc6MQ';
		    _feedback_url = window.location.href;
		    _feedback_item_identifier  = '';
		    _feedback_accession_number = book_data.designation || '';
		    _feedback_rg_number        = '';
		    _feedback_item_title       = book_data.title || '';
		    _feedback_user_ip          = user_ip || '';
		    _google_form_path = 'https://docs.google.com/a/ushmm.org/spreadsheet/viewform?formkey=' + google_form_key;
		    _google_form_path_complete  = _google_form_path;
		    _google_form_path_complete += '&entry_0='  + encodeURIComponent(_feedback_url);
		    _google_form_path_complete += '&entry_1='  + encodeURIComponent(_feedback_item_identifier);
		    _google_form_path_complete += '&entry_9='  + encodeURIComponent(_feedback_item_title);
		    _google_form_path_complete += '&entry_10=' + encodeURIComponent(_feedback_accession_number);
		    _google_form_path_complete += '&entry_12=' + encodeURIComponent(_feedback_rg_number);
		    _google_form_path_complete += '&entry_2='  + encodeURIComponent(_feedback_user_ip);
		    return _google_form_path_complete;
		};

	    $('#feedback_button').attr('href', oara_build_feedback_url());  // needs to be executed after page changes (e.g. with ajax)

	})

app/views/online_pages/edit.html.erb
<%= form_tag(online_page_path(@online_page), :method => :put) do %>
	<%= label_tag('digital_asset[page_number]', 'Page number:') %>
	<%= text_field_tag('digital_asset[page_number]', @online_page.digital_asset.page_number ) %>

	<%= label_tag('digital_asset[page_transcript]', 'Transcript:') %>
	<%= text_area_tag('digital_asset[page_transcript]', @online_page.digital_asset.page_transcript) %>

	<%= submit_tag('Update') %>

<% end %>

app/views/online_pages/index.html.haml
Book Pages:
%table
	%tr
		%td Digital Asset Designation
		%td Page Number
		/ %td Page Side
		/ %td Page Title
		%td Page Transcript
	- @online_pages.sort_by {|a| a.digital_asset.designation.to_i  }.each do |page|
		%tr
			%td= link_to(page.digital_asset.designation, page)
			%td= link_to(page.digital_asset.designation, {:controller => 'online_pages', :action => 'edit', :id => page.id})
			%td= page.digital_asset.page_number
			/ %td= page.digital_asset.page_side
			/ %td= page.digital_asset.page_title
			%td= page.digital_asset.page_transcript

app/views/online_pages/show.html.erb
<% content_for :header do %>
	<h1><%= @online_book.title %> <%= @online_book.title %></h1>
<% end %>


<% content_for :page_area do %>
	<%= render 'scripts_partial' %>
		<!-- <a href="/online_books/zoom_page/<%= @online_book.designation %>/<%= @online_page[:designation] %>"> -->
		<a href="http://collections.ushmm.org/webcollections/full//2001.62.14/2001.62.14_0007.jpg">
			<!-- <noimg src="<%= @online_page[:url] %>" /> -->
			<div>
				<img src="http://collections.ushmm.org/webcollections/full//2001.62.14/2001.62.14_0007.jpg"/>
				<!-- <img src="http://www.ushmm.org/m/img/2413438-640x410.jpg"/> -->
			</div>

		</a>
<% end %>

<% content_for :thumb_area do %>
	<ul style="margin-top: 3px; margin-bottom: 0px;">
		<% @page_num_array.each do |page_id| %>
			<% page = @pages_hash[page_id] %>
			<li style="display:inline; list-style-type:none; padding-right:10px; padding-bottom:0; margin-top: 0;">
				<div style="display:inline-block; border: 1px solid green; margin: 0;">
					<img id="thumb_#<%= page_id %>"
						data-original="<%= page[:derivative_url] %>"
						src="<%= page[:derivative_url] %>"
						style="height:<%= page[:derivative_height].to_s %>; width:<%= page[:derivative_width].to_s %>; margin: 0;"
						class='lazy' data-page_id=<%= page_id %>>
					<div class="page_designation">
						<%= page[:designation] %>
					</div>
				</div>
			</li>
		<% end %>
	</ul>
<% end %>


<% content_for :info_area do %>
	<div id="page_transcript_heading">
		Page Transcript
	</div>
	<div id="page_transcript">
		<%= @online_page[:transcript] %>
	</div>

		<a id="thumbnails_button" href="/learn/holocaust-encyclopedia/" class="ushmm_button">&lt;&nbsp;Thumbnails</a>
		<a id="feedback_button" href="/learn/holocaust-encyclopedia/" class="ushmm_button">Feedback</a>
		<a id="terms_of_use_button" href="http://www.ushmm.org/copyright-and-legal-information/terms-of-use" target="_blank" class="ushmm_button">Terms&nbsp;of&nbsp;Use</a>

		<a id="transcript_button" href="/learn/holocaust-encyclopedia/" class="ushmm_button">Page&nbsp;Transcript</a>
		<a id="learn_more_button" href="http://www.ushmm.org/information/exhibitions/online-features/special-focus/the-alfred-rosenberg-diary" class="ushmm_button historical">Learn&nbsp;More</a>
		<a id="catalog_record_button" href="/learn/holocaust-encyclopedia/" class="ushmm_button">Catalog&nbsp;Record</a>

		<a id="prev_button" href="/learn/holocaust-encyclopedia/" class="ushmm_button">&lt;&nbsp;Prev</a>
		<a id="zoom_button" href="<%= @online_page[:url] %>" class="ushmm_button"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="20px" height="16px" viewBox="0 0 512 512" enable-background="new 0 0 512 512" xml:space="preserve">

				<path fill="#ffffff" fill-rule="evenodd" clip-rule="evenodd" d="M497.914,497.914c-18.783,18.781-49.226,18.781-68.008,0l-84.863-84.864
					c-34.889,22.366-76.131,35.718-120.66,35.718C100.468,448.768,0,348.314,0,224.384S100.468,0,224.383,0
					c123.931,0,224.384,100.453,224.384,224.384c0,44.529-13.352,85.771-35.718,120.675l84.864,84.848
					C516.695,448.689,516.695,479.131,497.914,497.914z M224.383,64.11c-88.511,0-160.274,71.763-160.274,160.274
					c0,88.526,71.763,160.274,160.274,160.274c88.527,0,160.274-71.748,160.274-160.274C384.657,135.873,312.91,64.11,224.383,64.11z
					 M256.438,320.548h-64.109v-64.109h-64.109v-64.109h64.109v-64.11h64.109v64.11h64.11v64.109h-64.11V320.548z"/>
			</svg></a>
		<a id="next_button" href="/learn/holocaust-encyclopedia/" class="ushmm_button">Next&nbsp;&gt;</a>

<% end %>